config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'books#top'
get "books" => "books#index"
post "books" => "books#create"
get 'books/:id' => 'books#show', as: 'book'
get 'books/:id/edit' => 'books#edit', as: 'edit_book'
patch 'books/:id' => 'books#update', as: 'update_book'
delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book)
    else
      @books = Book.all
      render ("books/index")
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully update."
    redirect_to book_path(@book)
  else render :edit
  end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <div>
    <ul>
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved</h3>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      <% end %>
    </ul>
  </div>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>body</h4>
  <%= f.text_area :body %>
  <div>
  <%= f.submit 'Update Book' %>
  </div>
  <span class="btn"><%= link_to "Show", book_path(@book.id) %></span>
  <span>|</span>
  <span class="btn"><%= link_to("Back","/books") %></span>
<% end %>

app/views/books/index.html.erb
<main>
  <p class="flash-message"><%= flash[:notice] %></p>
  <h3 class="main-logo">Books</h3>
  <table>
  <thead>
  <tr>
  <th class="title">Title</th>
  <th class="body">Body</th>
  <th></th>
  </tr>
  </thead>

　<tbody>
　<% @books.each do |book| %>
　<tr>
　<td>
　<%= book.title %>
　</td>
　<td>
　<%= book.body %>
　</td>
　<td>
　<span class="btn">
　<%= link_to "show", book_path(book.id) %>
　</span>
　<span class="btn">
　<%= link_to "edit", edit_book_path(book.id) %>
　</span>
　<span class="btn">
　<%= link_to "destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
　</span>
　</td>
　</tr>
　<% end %>
　</tbody>
　</table>


　　<%= form_for(@book) do |f| %>
　　<h1 class="newbook">New Book</h1>
　　  <% if @book.errors.any? %>
  　  　<div>
   　  　<ul>
     　　 <h3><%= @book.errors.count %> errors prohibited this obj from being saved</h3>
       　　 <% @book.errors.full_messages.each do |message| %>
        　　<li><%= message %></li>
     　　　 <% end %>
    　　</ul>
     </div>
　　<% end %>

　<h4 class="new-form">Title</h4>
　<%= f.text_field :title %>

　<h4 class="new-form">Body</h4>
　<%= f.text_area :body %>

　<br><%= f.submit 'Create Book' %></br>

　<% end %>
</main>

app/views/books/show.html.erb
<div class="show">
  <div class="show-main">
    <p class="flash-message"><%= flash[:notice] %></p>
    <div class="show-title">
      <span class="show-title2">title:</span>
      <span class="title-text"><%= @book.title %></span>
    </div>
    <div class="show-body">
      <span class="show-body2">body:</span>
      <span class="body-text"><%= @book.body %></span>
    </div>
  </div>
  <span class="btn"><%= link_to "Edit", edit_book_path(@book.id) %></span>
  <span>|</span>
  <span class="btn"><%= link_to("Back","/books") %></span>
</show>

app/views/books/top.html.erb
<div class="top-page">
  <h1>ようこそ Bookersへ！</h1>
  <div class="top-text">
      <p><b>Bookers</b> では、さまざまな書籍に関するあなたの意見や</P>
      <p>印象を共有し交換することができます</p>
      <span class="btn"><%= link_to("start","/books") %></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>